image: debian:stable

build:
  script:
    - apt-get update && apt-get -y install python3 python3-venv default-jre-headless make wget bdf2psf
    - python3 -m venv bdflib-venv
    - ./bdflib-venv/bin/pip install bdflib
    - wget https://github.com/kreativekorp/bitsnpicas/releases/download/v2.0.2/BitsNPicas.jar
    - PATH=$PWD/bdflib-venv/bin:$PATH make
    - bdf2psf tmp/topaz_unicode_ks13_regular.bdf /usr/share/bdf2psf/standard.equivalents /usr/share/bdf2psf/ascii.set+/usr/share/bdf2psf/linux.set+/usr/share/bdf2psf/useful.set 512 topaz_unicode_ks13-16.psf
  artifacts:
    name: "topaz-unicode"
    paths:
      - ./*.ttf
      - ./*.psf
      - ./LICENSE
