image: debian:stable

build:
  script:
    - apt-get update && apt-get -y install python3 python3-venv default-jre-headless make
    - python3 -m venv bdflib-venv
    - ./bdflib-venv/bin/pip install bdflib
    - PATH=$PWD/bdflib-venv/bin:$PATH make
  artifacts:
    paths:
      - ./*.ttf
